config/routes.rb
Rails.application.routes.draw do
  root to: 'blogs#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users, only: %i[new create]
  resources :blogs do
    post :published, on: :member
    post :unpublished, on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  extend Enumerize

  validates :title, presence: true, length: { maximum: 20 }
  validates :content, presence: true, length: { maximum: 100 }

  enumerize :read, in: { published: 0, unpublished: 1 }, default: 0, scope: true

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, length: { maximum: 30 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  validates :password_digest, presence: true

  has_secure_password

  has_many :blogs, dependent: :destroy

  def feed
    Blog.with_read(:published).or(Blog.where(user: id)).preload(:user).order(created_at: :desc)
  end

  def own?(object)
    id == object.user_id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :info, :warning, :danger
  before_action :login_required
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end


  def login_required
    redirect_to login_path unless current_user
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = current_user.feed
  end

  def new
    @blog = current_user.blogs.new
  end

  def create
    @blog = current_user.blogs.new(blog_params)
    if @blog.save
      redirect_to blogs_path, success: '投稿に成功しました'
    else
      flash.now[:danger] = '投稿に失敗しました'
      render :new
    end
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def edit
    @blog = current_user.blogs.find(params[:id])
  end

  def update
    @blog = current_user.blogs.find(params[:id])
    if @blog.update(blog_params)
      redirect_to root_path, success: '投稿を更新しました'
    else
      flash.now[:danger] = '更新に失敗しました'
      render :edit
    end
  end

  def destroy
    @blog = current_user.blogs.find(params[:id])
    @blog.destroy!
    redirect_to root_path, success: '投稿を削除しました'
  end

  def published
    @blog = current_user.blogs.find(params[:id])
    @blog.read = :published
    @blog.save!
  end

  def unpublished
    @blog = current_user.blogs.find(params[:id])
    @blog.read = :unpublished
    @blog.save!
  end


  private

  def blog_params
    params.require(:blog).permit(:title, :content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: %i[new create]

  def new; end

  def create
    user = User.find_by(email: session_params[:email])
    # ユーザーがnilである可能性があるのでぼっち演算子
    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to root_path, success: 'ログインしました'
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to login_path, notice: 'ログアウトしました'
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path, success: '登録に成功しました'
    else
      flash.now[:dander] = '登録に失敗しました'
      render :new
    end
  end

  def show; end

  private

  def user_params
    params.require(:user).permit(:username, :age, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blogs/_blog.html.slim
div id = "blog-#{blog.id}"
  section.flex.flex-row.flex-wrap.mx-auto
    .transition-all.duration-150.flex.w-full.px-4.py-6.md_w-1-of-2.lg_w-1-of-3
      .flex.flex-col.items-stretch.min-h-full.pb-4.mb-6.transition-all.duration-150.bg-white.rounded-lg.shadow-lg.hover_shadow-2xl
        .md_flex-shrink-0
        hr.border-gray-300
          = link_to blog_path(blog), class: "hover:underline" do
            .flex.flex-wrap.items-center.flex-1.px-4.py-1.text-center.mx-auto
              h2.text-2xl.font-bold.tracking-normal.text-gray-800
                = blog.title
        hr.border-gray-300
          p.flex.flex-row.flex-wrap.w-full.px-4.py-2.overflow-hidden.text-sm.text-justify.text-gray-700
            = blog.content[0,20]
        hr.border-gray-300
          section.px-4.py-2.mt-2
            .flex.items-center.justify-between
              .flex.flex-col.mx-2
                = link_to '#', class: "font-semibold text-gray-700 hover:underline" do
                  = blog.user.username
                  span.mx-1.text-xs.text-gray-600
                    = blog.user&.age
        p.mt-1.text-xs.text-gray-600
            = l blog.created_at, format: :short
        - if current_user.own?(blog)
          section.px-4.py-2.mt-2
            = link_to '編集', edit_blog_path(blog), class: "edit-button focus:outline-none text-white text-sm py-2.5 px-5 rounded-md bg-green-500 hover:bg-green-600 hover:shadow-lg"
          section.px-4.py-2.mt-2
            = link_to '削除', blog_path(blog), method: :delete, data: {confirm: "本当に削除しますか？どうなっても知りませんよ"}, class: "delete-button focus:outline-none text-white text-sm py-2.5 px-5 rounded-md bg-red-500 hover:bg-red-600 hover:shadow-lg"

app/views/blogs/_form.html.slim
= form_with model: blog, class: 'flex flex-col pt-3 md_pt-8' do |f|
  = render 'shared/error_messages', object: blog
  .flex.flex-col.pt-4
    = f.label :title, class: 'text-lg font-black'
    = f.text_field :title, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus_outline-none focus_shadow-outline', placeholder: '最近の出来事など'
  .flex.flex-col.pt-4
    = f.label :content, class: 'text-lg font-black'
    = f.text_area :content, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus_outline-none focus_shadow-outline', placeholder: '本文'
  = f.submit '投稿', class: 'bg-black text-white font-bold text-lg hover_bg-gray-700 p-2 mt-8'

app/views/blogs/_published.html.slim
= link_to published_blog_path(blog), remote: true, method: :post do
  .fas.fa-flag

app/views/blogs/_read_area.html.slim
div id = "read_area-#{blog.id}"
  - if blog.read.published?
    = render 'unpublished', blog: blog
  -else
    = render 'published', blog: blog

app/views/blogs/_unpublished.html.slim
= link_to unpublished_blog_path(blog),remote: true, method: :post do
  .far.fa-flag

app/views/blogs/edit.html.slim
.w-full.md_w-1-of-2.flex.flex-col
  .flex.justify-center.md_justify-start.pt-12.md_pl-12.md_-mb-12
    = link_to 'RspecPractice', '#', class: 'bg-black text-white font-bold text-xl p-4'
  .flex.flex-col.justify-center.md_justify-start.my-auto.pt-8.md_pt-0.px-8.md_px-24.lg_px-32
    p.text-center.text-3xl.font-black
      | Let's post
      br
      | Have a nice day !
      = render 'form', blog: @blog
.w-1-of-2.shadow-2xl
  = image_tag '/blog3.jpeg', class: 'object-cover w-full h-screen hidden md_block', size: '30×30'

app/views/blogs/index.html.slim
= render @blogs

app/views/blogs/new.html.slim
.w-full.md_w-1-of-2.flex.flex-col
  .flex.justify-center.md_justify-start.pt-12.md_pl-12.md_-mb-12
    = link_to 'RspecPractice', '#', class: 'bg-black text-white font-bold text-xl p-4'
  .flex.flex-col.justify-center.md_justify-start.my-auto.pt-8.md_pt-0.px-8.md_px-24.lg_px-32
    p.text-center.text-3xl.font-black
      | Let's post
      br
      | Have a nice day !
      = render 'form', blog: @blog
.w-1-of-2.shadow-2xl
  = image_tag '/blog3.jpeg', class: 'object-cover w-full h-screen hidden md_block', size: '30×30'

app/views/blogs/published.js.slim
| $("#read_area-#{@blog.id}").html("#{ j(render 'unpublished', blog: @blog)}");

app/views/blogs/show.html.slim
.max-w-screen-lg.mx-auto
  .mt-12
    .flex.flex-wrap.md_flex-no-wrap.space-x-0.md_space-x-6.mb-16
      .mb-4.lg_mb-0.p-4.lg_p-0.w-full.md_w-4-of-7.relative.rounded.block
        = image_tag '/blog2.jpeg', class: "rounded-md object-cover w-full h-64"
        span.text-green-700.text-sm.hidden.md_block.mt-4
          = l @blog.created_at, format: :short
        h1.text-gray-800.text-4xl.font-bold.mt-2.mb-2.leading-tight
          = @blog.title
        p.text-gray-600.mb-4
          = @blog.content
      - if current_user.own?(@blog)
        section
          = link_to '編集', edit_blog_path(@blog), class: "focus:outline-none text-white text-sm py-2.5 px-5 rounded-md bg-green-500 hover:bg-green-600 hover:shadow-lg"
        section
          = link_to '削除', blog_path(@blog), method: :delete, data: { confirm: "本当に削除しますか？どうなっても知りませんよ" }, class: "focus:outline-none text-white text-sm py-2.5 px-5 rounded-md bg-red-500 hover:bg-red-600 hover:shadow-lg"
        section
          = render 'read_area', blog: @blog

app/views/blogs/unpublished.js.slim
| $("#read_area-#{@blog.id}").html("#{ j(render 'published', blog: @blog)}");

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | RspecPractice
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body.bg-white.font-family-karla.h-screen
    = render 'shared/header'
    = render 'shared/flash_messages'
    .w-full.flex.flex-wrap
      = yield

app/views/shared/_error_messages.html.slim
- if object.errors.any?
  .alert.alert-danger#error_messsages
    .bg-indigo-900.text-center.py-4.lg_px-4.rounded-lg
      .flex.rounded-full.bg-indigo-500.uppercase.px-2.py-1.text-xs.font-bold.mr-3
        span.font-semibold.mr-2.text-left.flex-auto
          - object.errors.full_messages.each do |message|
            ul.list-none
              li.text-pink-500 = message
        svg.fill-current.opacity-75.h-4.w-4[xmlns="http://www.w3.org/2000/svg" viewbox="0 0 20 20"]
          path[d="M12.95 10.707l.707-.707L8 4.343 6.586 5.757 10.828 10l-4.242 4.243L8 15.657l4.95-4.95z"]

app/views/shared/_flash_messages.html.slim
- flash.each do |message_type, message|
  div class = "alert alert-#{message_type}"
    .bg-indigo-900.text-center.py-4.lg_px-4
      .flex.rounded-full.bg-indigo-500.uppercase.px-2.py-1.text-xs.font-bold.mr-3
        span.flex.rounded-full.bg-indigo-500.uppercase.px-2.py-1.text-xs.font-bold.mr-3
        = message_type
        span.font-semibold.mr-2.text-left.flex-auto
        = message
        svg.fill-current.opacity-75.h-4.w-4[xmlns="http://www.w3.org/2000/svg" viewbox="0 0 20 20"]
          path[d="M12.95 10.707l.707-.707L8 4.343 6.586 5.757 10.828 10l-4.242 4.243L8 15.657l4.95-4.95z"]

app/views/shared/_header.html.slim
nav.bg-gray-900.p-4.mt-0.w-full
  .container.mx-auto.flex.items-center
    .flex.text-white.font-extrabold
      = link_to '#', class: "flex text-white text-base no-underline hover_text-white hover_no-underline" do
        |  👻
        span.hidden.w-0.md_w-auto.md_block.pl-1
          | RspecPractice
    .flex.pl-4.text-sm
      ul.list-reset.flex.justify-between.flex-1.md_flex-none.items-center
        - if current_user
          li.mr-2
            = link_to 'HOME', blogs_path, class: "inline-block py-2 px-2 text-white no-underline"
          li.mr-2
            = link_to 'POST', new_blog_path, class:  "inline-block text-gray-600 no-underline hover_text-gray-200 hover_text-underline py-2 px-2"
          li.mr-2
            = link_to 'LOGOUT', logout_path, method: :delete, class: "inline-block text-gray-600 no-underline hover_text-gray-200 hover_text-underline py-2 px-2"
        - else
          li.mr-2
            = link_to 'sign up', blogs_path, class: "inline-block py-2 px-2 text-white no-underline"
          li.mr-2
            = link_to 'login', new_blog_path, class: "inline-block text-gray-600 no-underline hover_text-gray-200 hover_text-underline py-2 px-2"

app/views/users/new.html.slim
.w-full.md_w-1-of-2.flex.flex-col
  .flex.justify-center.md_justify-start.pt-12.md_pl-12.md_-mb-12
    = link_to 'RspecPractice', '#', class: 'bg-black text-white font-bold text-xl p-4'
  .flex.flex-col.justify-center.md_justify-start.my-auto.pt-8.md_pt-0.px-8.md_px-24.lg_px-32
    p.text-center.text-3xl.font-black
      | Join Us.
      br
      | Would you like to join us?
      = form_with model: @user, class: 'flex flex-col pt-3 md_pt-8' do |f|
        = render 'shared/error_messages', object: @user
        .flex.flex-col.pt-4
          = f.label :username, class: 'text-lg font-black'
          = f.text_field :username, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus_outline-none focus_shadow-outline', placeholder: '名前'
        .flex.flex-col.pt-4
          = f.label :age, class: 'text-lg font-black'
          = f.text_field :age, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus_outline-none focus_shadow-outline', placeholder: '任意'
        .flex.flex-col.pt-4
          = f.label :email, class: 'text-lg font-black'
          = f.email_field :email, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus_outline-none focus_shadow-outline', placeholder: "your@email.com"
        .flex.flex-col.pt-4
          = f.label :password, class: 'text-lg font-black'
          = f.password_field :password, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus_outline-none focus_shadow-outline', placeholder: "Password"
        .flex.flex-col.pt-4
          = f.label :password_confirmation, class: 'text-lg font-black'
          = f.password_field :password_confirmation, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus_outline-none focus_shadow-outline', placeholder: "Password"
        = f.submit '登録', class: 'bg-black text-white font-bold text-lg hover_bg-gray-700 p-2 mt-8'
      .text-center.pt-12.pb-12
        p
          | Already have an account?
        = link_to 'Log in here.', login_path, class: 'underline font-semibold'
.w-1-of-2.shadow-2xl
  = image_tag '/demo5.jpeg', class: 'object-cover w-full h-screen hidden md_block', size: '30×30'